/**
 * 퀘스트 초기 데이터
 * id는 ACTION_QUEST_MAP과 동일한 고정 ID 사용
 */

export interface QuestSeedItem {
    id: string
    title: string
    description: string
    type: 'DAILY' | 'WEEKLY' | 'ACHIEVEMENT'
    category: string
    icon: string
    targetCount: number
    rewardGp: number
}

export const INITIAL_QUESTS: QuestSeedItem[] = [
    // ── DAILY ─────────────────────────────────────────────────────
    {
        id: 'dq-login',
        title: '오늘의 출석 체크',
        description: '오늘 E-Sport Information Collection에 방문하세요.',
        type: 'DAILY',
        category: 'GENERAL',
        icon: '📅',
        targetCount: 1,
        rewardGp: 10,
    },
    {
        id: 'dq-predict-1',
        title: '오늘의 예측',
        description: '오늘 LCK 경기를 1번 예측하세요.',
        type: 'DAILY',
        category: 'PREDICTION',
        icon: '🎯',
        targetCount: 1,
        rewardGp: 15,
    },
    {
        id: 'dq-predict-3',
        title: '예측 마니아',
        description: '오늘 LCK 경기를 3번 예측하세요.',
        type: 'DAILY',
        category: 'PREDICTION',
        icon: '🎲',
        targetCount: 3,
        rewardGp: 30,
    },
    {
        id: 'dq-daily-quiz',
        title: '오늘의 퀴즈',
        description: '오늘의 LCK 퀴즈를 풀어보세요.',
        type: 'DAILY',
        category: 'QUIZ',
        icon: '🧠',
        targetCount: 1,
        rewardGp: 10,
    },
    {
        id: 'dq-check-match',
        title: '경기 일정 확인',
        description: '오늘의 LCK 경기 일정을 확인하세요.',
        type: 'DAILY',
        category: 'GENERAL',
        icon: '📋',
        targetCount: 1,
        rewardGp: 5,
    },
    {
        id: 'dq-ai-chat',
        title: 'AI 분석관 활용',
        description: 'AI 분석관에게 LCK 경기를 물어보세요.',
        type: 'DAILY',
        category: 'GENERAL',
        icon: '🤖',
        targetCount: 1,
        rewardGp: 10,
    },
    {
        id: 'dq-check-player',
        title: '선수 정보 확인',
        description: '오늘 선수 상세 페이지를 방문하세요.',
        type: 'DAILY',
        category: 'GENERAL',
        icon: '👤',
        targetCount: 1,
        rewardGp: 5,
    },

    // ── WEEKLY ────────────────────────────────────────────────────
    {
        id: 'wq-login-5',
        title: '꾸준한 팬',
        description: '이번 주 5일 이상 방문하세요.',
        type: 'WEEKLY',
        category: 'GENERAL',
        icon: '📆',
        targetCount: 5,
        rewardGp: 50,
    },
    {
        id: 'wq-predict-5',
        title: '주간 예측왕',
        description: '이번 주 5번 이상 경기를 예측하세요.',
        type: 'WEEKLY',
        category: 'PREDICTION',
        icon: '🏆',
        targetCount: 5,
        rewardGp: 60,
    },
    {
        id: 'wq-predict-correct',
        title: '적중의 신',
        description: '이번 주 예측 3경기를 맞혀보세요.',
        type: 'WEEKLY',
        category: 'PREDICTION',
        icon: '✅',
        targetCount: 3,
        rewardGp: 80,
    },
    {
        id: 'wq-check-history',
        title: '전적 탐험가',
        description: '이번 주 팀 상세 페이지를 방문하세요.',
        type: 'WEEKLY',
        category: 'GENERAL',
        icon: '📊',
        targetCount: 1,
        rewardGp: 15,
    },

    // ── ACHIEVEMENT ───────────────────────────────────────────────
    {
        id: 'ach-login-7',
        // ✅ M-15 수정: 날짜 연속성 미검증 → 누적 방문으로 설명 수정
        title: '7일 방문',
        description: 'E-Sport Information Collection을 총 7번 방문하세요.',
        type: 'ACHIEVEMENT',
        category: 'GENERAL',
        icon: '🔥',
        targetCount: 7,
        rewardGp: 100,
    },
    {
        id: 'ach-login-30',
        title: '30일 방문',
        description: 'E-Sport Information Collection을 총 30번 방문하세요.',
        type: 'ACHIEVEMENT',
        category: 'GENERAL',
        icon: '💎',
        targetCount: 30,
        rewardGp: 500,
    },
    {
        id: 'ach-predict-first',
        title: '첫 예측',
        description: '생애 첫 경기 예측을 완료하세요.',
        type: 'ACHIEVEMENT',
        category: 'PREDICTION',
        icon: '🌟',
        targetCount: 1,
        rewardGp: 50,
    },
    {
        id: 'ach-predict-10',
        title: '예측 10경기',
        description: '총 10경기 이상 예측하세요.',
        type: 'ACHIEVEMENT',
        category: 'PREDICTION',
        icon: '📈',
        targetCount: 10,
        rewardGp: 100,
    },
    {
        id: 'ach-predict-50',
        title: '예측 50경기',
        description: '총 50경기 이상 예측하세요.',
        type: 'ACHIEVEMENT',
        category: 'PREDICTION',
        icon: '🎖️',
        targetCount: 50,
        rewardGp: 300,
    },
    {
        id: 'ach-correct-streak-5',
        title: '5연속 적중',
        description: '5경기 연속 예측을 맞혀보세요.',
        type: 'ACHIEVEMENT',
        category: 'PREDICTION',
        icon: '⚡',
        targetCount: 5,
        rewardGp: 200,
    },
    {
        id: 'ach-correct-streak-10',
        title: '10연속 적중',
        description: '10경기 연속 예측을 맞혀보세요.',
        type: 'ACHIEVEMENT',
        category: 'PREDICTION',
        icon: '👑',
        targetCount: 10,
        rewardGp: 500,
    },
    {
        id: 'ach-ai-10',
        title: 'AI 단골',
        description: 'AI 분석관을 10번 이용하세요.',
        type: 'ACHIEVEMENT',
        category: 'GENERAL',
        icon: '🤖',
        targetCount: 10,
        rewardGp: 100,
    },
    {
        id: 'ach-quiz-7',
        title: '퀴즈 마스터',
        // ✅ 수정: 누적 카운트 로직에 맞게 설명 수정 (7일 연속 → 7일 이상)
        description: '오늘의 퀴즈를 7일 이상 풀어보세요.',
        type: 'ACHIEVEMENT',
        category: 'QUIZ',
        icon: '🧠',
        targetCount: 7,
        rewardGp: 150,
    },
    {
        id: 'ach-cosmetic-first',
        title: '첫 코스메틱 구매',
        description: '상점에서 첫 코스메틱 아이템을 구매하세요.',
        type: 'ACHIEVEMENT',
        category: 'GENERAL',
        icon: '🛍️',
        targetCount: 1,
        rewardGp: 50,
    },

    // ── QUIZ ──────────────────────────────────────────────────────
    {
        id: 'ach-quiz-correct-10',
        title: '퀴즈 달인',
        description: '오늘의 퀴즈에서 10번 정답을 맞히세요.',
        type: 'ACHIEVEMENT',
        category: 'QUIZ',
        icon: '🎓',
        targetCount: 10,
        rewardGp: 100,
    },
    {
        id: 'ach-quiz-correct-30',
        title: '지식의 신',
        description: '오늘의 퀴즈에서 30번 정답을 맞히세요.',
        type: 'ACHIEVEMENT',
        category: 'QUIZ',
        icon: '🏅',
        targetCount: 30,
        rewardGp: 300,
    },
    {
        id: 'ach-quiz-30days',
        title: '퀴즈 30일 도전',
        description: '30일 이상 오늘의 퀴즈를 풀어보세요.',
        type: 'ACHIEVEMENT',
        category: 'QUIZ',
        icon: '📚',
        targetCount: 30,
        rewardGp: 500,
    },

    // ── PREDICTION (추가) ─────────────────────────────────────────
    {
        id: 'wq-predict-correct-5',
        title: '예측 고수',
        description: '이번 주 예측을 5번 맞혀보세요.',
        type: 'WEEKLY',
        category: 'PREDICTION',
        icon: '🎯',
        targetCount: 5,
        rewardGp: 120,
    },
    {
        id: 'ach-predict-100',
        title: '예측 100경기',
        description: '총 100경기 이상 예측하세요.',
        type: 'ACHIEVEMENT',
        category: 'PREDICTION',
        icon: '💯',
        targetCount: 100,
        rewardGp: 500,
    },

    // ── GENERAL (추가) ────────────────────────────────────────────
    {
        id: 'ach-login-100',
        title: '100일 팬',
        description: 'E-Sport Information Collection을 총 100일 방문하세요.',
        type: 'ACHIEVEMENT',
        category: 'GENERAL',
        icon: '🏆',
        targetCount: 100,
        rewardGp: 1000,
    },
    {
        id: 'wq-ai-chat-3',
        title: '주간 AI 활용',
        description: '이번 주 AI 분석관을 3번 이용하세요.',
        type: 'WEEKLY',
        category: 'GENERAL',
        icon: '🤖',
        targetCount: 3,
        rewardGp: 30,
    },

    // ── SHOP / COSMETIC ───────────────────────────────────────────────────
    {
        id: 'ach-shop-first',
        title: '나만의 스타일',
        description: '상점에서 코스메틱 아이템을 처음으로 구매하세요.',
        type: 'ACHIEVEMENT',
        category: 'COLLECTION',
        icon: '🛍️',
        targetCount: 1,
        rewardGp: 100,
    },
    {
        id: 'ach-shop-5',
        title: '수집가',
        description: '코스메틱 아이템을 5개 이상 보유하세요.',
        type: 'ACHIEVEMENT',
        category: 'COLLECTION',
        icon: '💎',
        targetCount: 5,
        rewardGp: 300,
    },

    // ── SOCIAL ────────────────────────────────────────────────────────────
    {
        id: 'dq-community-post',
        title: '오늘의 글쓰기',
        description: '커뮤니티에 게시글을 작성하세요.',
        type: 'DAILY',
        category: 'SOCIAL',
        icon: '📝',
        targetCount: 1,
        rewardGp: 20,
    },
    {
        id: 'dq-community-comment',
        title: '댓글 달기',
        description: '커뮤니티 게시글에 댓글을 달아보세요.',
        type: 'DAILY',
        category: 'SOCIAL',
        icon: '💬',
        targetCount: 1,
        rewardGp: 10,
    },
    {
        id: 'wq-community-5',
        title: '활발한 소통',
        description: '이번 주 커뮤니티를 5번 이용하세요 (글쓰기 또는 댓글).',
        type: 'WEEKLY',
        category: 'SOCIAL',
        icon: '🤝',
        targetCount: 5,
        rewardGp: 60,
    },
    {
        id: 'ach-follow-first',
        title: '첫 팔로우',
        description: '다른 유저를 처음 팔로우하세요.',
        type: 'ACHIEVEMENT',
        category: 'SOCIAL',
        icon: '👥',
        targetCount: 1,
        rewardGp: 30,
    },
    {
        id: 'ach-post-10',
        title: '커뮤니티 기여자',
        description: '커뮤니티에 게시글 10개를 작성하세요.',
        type: 'ACHIEVEMENT',
        category: 'SOCIAL',
        icon: '✍️',
        targetCount: 10,
        rewardGp: 200,
    },
]
