/**
 * LCK 데일리 퀴즈 초기 문항 데이터
 * 매일 한 문항씩 순환됩니다.
 */

export interface QuizSeedItem {
    question: string
    optionA: string
    optionB: string
    optionC?: string
    optionD?: string
    answer: string
    explanation?: string
    category: string
    difficulty: string
    gpReward: number
    orderIndex: number
}

export const INITIAL_QUIZ_QUESTIONS: QuizSeedItem[] = [
    {
        question: "LCK의 정식 명칭은 무엇인가요?",
        optionA: "League of Legends Champions Korea",
        optionB: "League of Legends Championship Korea",
        optionC: "LoL Champions Korea",
        optionD: "League Champions Korea",
        answer: "A",
        explanation: "LCK는 'League of Legends Champions Korea'의 약자로, 한국 최상위 LoL e스포츠 리그입니다.",
        category: "RULES",
        difficulty: "EASY",
        gpReward: 15,
        orderIndex: 0,
    },
    {
        question: "e스포츠에서 'ADC'가 의미하는 것은?",
        optionA: "Attack Damage Carry",
        optionB: "Ability Damage Core",
        optionC: "Advanced Damage Control",
        optionD: "Automated Damage Calculator",
        answer: "A",
        explanation: "ADC(Attack Damage Carry)는 물리 데미지를 주로 딜하는 원거리 딜러 포지션입니다.",
        category: "RULES",
        difficulty: "EASY",
        gpReward: 15,
        orderIndex: 1,
    },
    {
        question: "T1의 미드 라이너 'Faker'의 실명은?",
        optionA: "이상혁",
        optionB: "이재동",
        optionC: "박민규",
        optionD: "김동하",
        answer: "A",
        explanation: "Faker의 본명은 이상혁으로, T1 소속의 전설적인 미드 라이너입니다.",
        category: "TRIVIA",
        difficulty: "EASY",
        gpReward: 15,
        orderIndex: 2,
    },
    {
        question: "LoL 월드 챔피언십의 한국 별칭은?",
        optionA: "롤드컵",
        optionB: "월챔전",
        optionC: "세계대회",
        optionD: "리그컵",
        answer: "A",
        explanation: "LoL 월드 챔피언십은 팬들 사이에서 '롤드컵'이라고 불립니다.",
        category: "TRIVIA",
        difficulty: "EASY",
        gpReward: 15,
        orderIndex: 3,
    },
    {
        question: "LCK 정규 시즌에 참가하는 팀 수는?",
        optionA: "10개",
        optionB: "8개",
        optionC: "12개",
        optionD: "6개",
        answer: "A",
        explanation: "LCK는 10개의 팀이 참가하는 한국 최상위 LoL 리그입니다.",
        category: "RULES",
        difficulty: "EASY",
        gpReward: 15,
        orderIndex: 4,
    },
    {
        question: "다음 중 LCK(한국 리그) 소속 팀이 아닌 팀은?",
        optionA: "Team Liquid",
        optionB: "T1",
        optionC: "Gen.G",
        optionD: "KT Rolster",
        answer: "A",
        explanation: "Team Liquid는 북미 LCS 소속 팀으로, LCK(한국 리그) 소속이 아닙니다.",
        category: "TEAMS",
        difficulty: "NORMAL",
        gpReward: 20,
        orderIndex: 5,
    },
    {
        question: "LoL에서 정글러의 주요 역할은?",
        optionA: "맵을 이동하며 정글 몬스터를 처치하고 라인에 개입(갱킹)",
        optionB: "바텀 라인에서 파밍만 담당",
        optionC: "미드 라인에서 AP 딜러를 견제",
        optionD: "탑 라인에서 1:1 듀얼만 담당",
        answer: "A",
        explanation: "정글러는 라인 밖 정글 몬스터를 처치하며 갱킹(라인 개입)으로 팀을 지원하는 포지션입니다.",
        category: "RULES",
        difficulty: "EASY",
        gpReward: 15,
        orderIndex: 6,
    },
    {
        question: "LCK BO3(Best-of-3) 방식은?",
        optionA: "최대 3세트, 먼저 2세트 이기는 팀이 승리",
        optionB: "3세트 모두 이겨야 승리",
        optionC: "최대 5세트, 먼저 3세트 이기는 팀이 승리",
        optionD: "1세트 이기면 바로 승리",
        answer: "A",
        explanation: "BO3(Best-of-3)는 최대 3게임을 진행하며, 먼저 2게임을 이기는 팀이 시리즈를 가져갑니다.",
        category: "RULES",
        difficulty: "EASY",
        gpReward: 15,
        orderIndex: 7,
    },
    {
        question: "'Hanwha Life Esports'의 공식 팀 코드(약어)는?",
        optionA: "HLE",
        optionB: "HAN",
        optionC: "HLF",
        optionD: "HWL",
        answer: "A",
        explanation: "Hanwha Life Esports의 공식 LCK 팀 코드는 HLE입니다.",
        category: "TEAMS",
        difficulty: "NORMAL",
        gpReward: 20,
        orderIndex: 8,
    },
    {
        question: "LoL에서 '바론 나샤'를 처치하면 어떤 이점이 있나요?",
        optionA: "팀원 전체에게 강화 버프 부여 및 미니언 강화",
        optionB: "상대 넥서스에 즉시 데미지",
        optionC: "상대팀의 골드를 감소",
        optionD: "미니언 스폰이 일시 중단",
        answer: "A",
        explanation: "바론 나샤 처치 시 '바론 버프'를 획득해 미니언이 강화되고 팀이 전반적으로 강해집니다.",
        category: "RULES",
        difficulty: "NORMAL",
        gpReward: 20,
        orderIndex: 9,
    },
    {
        question: "LoL e스포츠에서 'BO5'는 무엇을 의미하나요?",
        optionA: "최대 5세트, 먼저 3세트 이기는 팀이 승리",
        optionB: "5세트 모두 이겨야 승리",
        optionC: "5분 안에 이기면 승리",
        optionD: "5명 중 과반수 찬성 시 항복",
        answer: "A",
        explanation: "BO5(Best-of-5)는 최대 5게임을 진행하며, 먼저 3게임을 이기는 팀이 승리합니다. 주로 결승전에서 사용됩니다.",
        category: "RULES",
        difficulty: "EASY",
        gpReward: 15,
        orderIndex: 10,
    },
    {
        question: "Gen.G의 공식 팀 코드(약어)는?",
        optionA: "GEN",
        optionB: "GNG",
        optionC: "GG",
        optionD: "GENG",
        answer: "A",
        explanation: "Gen.G의 공식 LCK 팀 코드는 GEN입니다.",
        category: "TEAMS",
        difficulty: "EASY",
        gpReward: 15,
        orderIndex: 11,
    },
    {
        question: "LCK에서 역대 가장 많은 우승을 차지한 팀은?",
        optionA: "T1 (구 SKT T1)",
        optionB: "KT Rolster",
        optionC: "Gen.G",
        optionD: "Hanwha Life",
        answer: "A",
        explanation: "T1(구 SKT T1)은 Faker(이상혁)를 필두로 LCK 역대 최다 우승을 차지한 팀입니다.",
        category: "HISTORY",
        difficulty: "EASY",
        gpReward: 15,
        orderIndex: 12,
    },
    {
        question: "LoL에서 '넥서스'란 무엇인가요?",
        optionA: "각 팀 기지의 핵심 건물로, 파괴하면 게임 승리",
        optionB: "정글 내 특수 몬스터",
        optionC: "아이템 상점의 이름",
        optionD: "소환사의 협곡 중앙 지형",
        answer: "A",
        explanation: "넥서스는 각 팀의 기지 핵심 건물로, 상대방 넥서스를 파괴하면 게임에서 승리합니다.",
        category: "RULES",
        difficulty: "EASY",
        gpReward: 15,
        orderIndex: 13,
    },
    {
        question: "LCK에서 플레이오프 진출 팀은 정규 시즌 기준 몇 위까지인가요?",
        optionA: "6위까지",
        optionB: "4위까지",
        optionC: "8위까지",
        optionD: "10위까지",
        answer: "A",
        explanation: "LCK 정규 시즌 상위 6팀이 플레이오프에 진출하며, 1-2위는 시드를 받아 라운드를 건너뜁니다.",
        category: "RULES",
        difficulty: "NORMAL",
        gpReward: 20,
        orderIndex: 14,
    },
    {
        question: "다음 중 LoL 포지션(역할)에 해당하지 않는 것은?",
        optionA: "어시스트 (Assist)",
        optionB: "탑 (Top)",
        optionC: "정글 (Jungle)",
        optionD: "서포터 (Support)",
        answer: "A",
        explanation: "LoL의 5가지 포지션은 탑, 정글, 미드, 원딜(ADC), 서포터입니다. '어시스트'는 통계 용어이지 포지션이 아닙니다.",
        category: "RULES",
        difficulty: "NORMAL",
        gpReward: 20,
        orderIndex: 15,
    },
    {
        question: "KT Rolster의 공식 팀 코드(약어)는?",
        optionA: "KT",
        optionB: "KTR",
        optionC: "KTL",
        optionD: "ROL",
        answer: "A",
        explanation: "KT Rolster의 공식 LCK 팀 코드는 KT입니다.",
        category: "TEAMS",
        difficulty: "EASY",
        gpReward: 15,
        orderIndex: 16,
    },
    {
        question: "LoL e스포츠 한국 리그(LCK)는 1년에 몇 번의 스플릿(시즌)으로 나뉘나요?",
        optionA: "2번 (Spring, Summer 또는 Split 1, Split 2)",
        optionB: "4번 (분기별)",
        optionC: "1번",
        optionD: "3번 (Spring, Summer, Fall)",
        answer: "A",
        explanation: "LCK는 보통 1년 2번 스플릿(Spring/Split1, Summer/Split2)으로 나뉘어 시즌이 진행됩니다.",
        category: "RULES",
        difficulty: "NORMAL",
        gpReward: 20,
        orderIndex: 17,
    },
    {
        question: "DRX의 공식 팀 코드(약어)는?",
        optionA: "DRX",
        optionB: "DRG",
        optionC: "DX",
        optionD: "DRA",
        answer: "A",
        explanation: "DRX(Dragon X)의 공식 LCK 팀 코드는 DRX입니다.",
        category: "TEAMS",
        difficulty: "EASY",
        gpReward: 15,
        orderIndex: 18,
    },
    {
        question: "LoL에서 '드래곤' 오브젝트를 처치하면 어떤 이점이 있나요?",
        optionA: "팀 전체 영구 스탯 강화 버프 누적",
        optionB: "상대팀의 미니언 일시 제거",
        optionC: "아군 구조물 즉시 수리",
        optionD: "지도 안개가 잠시 사라짐",
        answer: "A",
        explanation: "드래곤 처치 시 원소 속성에 따른 스탯 버프가 팀 전체에 영구 누적됩니다. 4마리 처치 시 '드래곤의 영혼'을 얻습니다.",
        category: "RULES",
        difficulty: "NORMAL",
        gpReward: 20,
        orderIndex: 19,
    },

    // ──────────────────────────────────────────────────────────────
    // 팀 공식 명칭 (EASY)
    // ──────────────────────────────────────────────────────────────
    {
        question: "DK의 정식 팀명은?",
        optionA: "Dplus KIA",
        optionB: "Damwon KIA",
        optionC: "Dragon KIA",
        optionD: "Dark KIA",
        answer: "A",
        explanation: "DK는 'Dplus KIA'의 약자입니다. 전 이름은 Damwon Gaming이었습니다.",
        category: "TEAMS",
        difficulty: "EASY",
        gpReward: 15,
        orderIndex: 20,
    },
    {
        question: "NS의 정식 팀명은?",
        optionA: "NONGSHIM RED FORCE",
        optionB: "NS RedForce Gaming",
        optionC: "Nongshim Esports",
        optionD: "Nongshim Redstar",
        answer: "A",
        explanation: "NS는 'NONGSHIM RED FORCE'의 약자로, 농심이 스폰서하는 LCK 팀입니다.",
        category: "TEAMS",
        difficulty: "EASY",
        gpReward: 15,
        orderIndex: 21,
    },
    {
        question: "HLE의 정식 팀명은?",
        optionA: "Hanwha Life Esports",
        optionB: "Hyundai Life Esports",
        optionC: "Hanjin Life Esports",
        optionD: "Hanwha League Esports",
        answer: "A",
        explanation: "HLE는 'Hanwha Life Esports'의 약자로, 한화생명보험이 운영하는 LCK 팀입니다.",
        category: "TEAMS",
        difficulty: "EASY",
        gpReward: 15,
        orderIndex: 22,
    },
    {
        question: "BFX의 정식 팀명은?",
        optionA: "BNK FEARX",
        optionB: "BNK FearX Gaming",
        optionC: "Busan FEARX",
        optionD: "BNK FX Esports",
        answer: "A",
        explanation: "BFX는 'BNK FEARX'의 약자로, BNK 금융그룹이 스폰서하는 팀입니다.",
        category: "TEAMS",
        difficulty: "NORMAL",
        gpReward: 20,
        orderIndex: 23,
    },
    {
        question: "BRO의 정식 팀명은?",
        optionA: "HANJIN BRION",
        optionB: "Brothers Esports",
        optionC: "Brion Blades",
        optionD: "BRO Gaming",
        answer: "A",
        explanation: "BRO는 'HANJIN BRION'의 약자로, 한진이 스폰서하는 LCK 팀입니다.",
        category: "TEAMS",
        difficulty: "NORMAL",
        gpReward: 20,
        orderIndex: 24,
    },
    {
        question: "DNS의 정식 팀명은?",
        optionA: "DN SOOPers",
        optionB: "Digital Now Soopers",
        optionC: "DNS Gaming",
        optionD: "DN Super Esports",
        answer: "A",
        explanation: "DNS는 'DN SOOPers'의 약자로, DN그룹과 인터넷 방송 플랫폼 SOOP이 함께하는 팀입니다.",
        category: "TEAMS",
        difficulty: "NORMAL",
        gpReward: 20,
        orderIndex: 25,
    },

    // ──────────────────────────────────────────────────────────────
    // 선수 개인 정보 (EASY~NORMAL)
    // ──────────────────────────────────────────────────────────────
    {
        question: "T1 소속 미드 라이너 'Faker'의 포지션은?",
        optionA: "미드 라이너",
        optionB: "원거리 딜러",
        optionC: "정글러",
        optionD: "서포터",
        answer: "A",
        explanation: "Faker(이상혁)는 T1 소속의 전설적인 미드 라이너입니다.",
        category: "PLAYERS",
        difficulty: "EASY",
        gpReward: 15,
        orderIndex: 26,
    },
    {
        question: "Gen.G 소속 미드 라이너 'Chovy'의 포지션은?",
        optionA: "미드 라이너",
        optionB: "서포터",
        optionC: "탑 라이너",
        optionD: "정글러",
        answer: "A",
        explanation: "Chovy(정지훈)는 Gen.G 소속의 미드 라이너로, 높은 CS 능력과 개인기로 유명합니다.",
        category: "PLAYERS",
        difficulty: "EASY",
        gpReward: 15,
        orderIndex: 27,
    },
    {
        question: "Gen.G 소속 원거리 딜러 'Ruler'의 포지션은?",
        optionA: "원거리 딜러(ADC)",
        optionB: "서포터",
        optionC: "미드 라이너",
        optionD: "정글러",
        answer: "A",
        explanation: "Ruler(박재혁)는 Gen.G 소속의 원거리 딜러로, 안정적인 플레이로 유명합니다.",
        category: "PLAYERS",
        difficulty: "EASY",
        gpReward: 15,
        orderIndex: 28,
    },
    {
        question: "Faker(이상혁)의 LoL 롤드컵(Worlds) 우승 횟수는?",
        optionA: "4회",
        optionB: "3회",
        optionC: "5회",
        optionD: "2회",
        answer: "A",
        explanation: "Faker는 2013, 2015, 2016, 2023년에 롤드컵에서 우승하여 총 4회 우승을 기록했습니다.",
        category: "PLAYERS",
        difficulty: "NORMAL",
        gpReward: 20,
        orderIndex: 29,
    },
    {
        question: "Gen.G 미드 라이너 Chovy의 실명은?",
        optionA: "정지훈",
        optionB: "정민혁",
        optionC: "정지호",
        optionD: "정진훈",
        answer: "A",
        explanation: "Chovy의 본명은 정지훈으로, Gen.G 소속의 뛰어난 미드 라이너입니다.",
        category: "PLAYERS",
        difficulty: "NORMAL",
        gpReward: 20,
        orderIndex: 30,
    },
    {
        question: "T1 서포터 'Keria'의 실명은?",
        optionA: "류민석",
        optionB: "박민규",
        optionC: "이재현",
        optionD: "김민성",
        answer: "A",
        explanation: "Keria의 본명은 류민석으로, T1 소속의 서포터입니다.",
        category: "PLAYERS",
        difficulty: "NORMAL",
        gpReward: 20,
        orderIndex: 31,
    },

    // ──────────────────────────────────────────────────────────────
    // LCK 역사 및 기록 (NORMAL~HARD)
    // ──────────────────────────────────────────────────────────────
    {
        question: "LCK 역대 최다 우승 팀은?",
        optionA: "T1 (구 SKT T1)",
        optionB: "KT Rolster",
        optionC: "Gen.G",
        optionD: "Hanwha Life Esports",
        answer: "A",
        explanation: "T1(구 SKT T1)은 Faker(이상혁)를 중심으로 LCK 역대 최다 우승을 기록한 팀입니다.",
        category: "HISTORY",
        difficulty: "EASY",
        gpReward: 15,
        orderIndex: 32,
    },
    {
        question: "Gen.G의 전신 팀 이름은?",
        optionA: "Samsung Galaxy",
        optionB: "SKT T1",
        optionC: "Rox Tigers",
        optionD: "KT Rolster",
        answer: "A",
        explanation: "Gen.G는 Samsung Galaxy를 전신으로 하며, 2017년 Gen.G로 리브랜딩되었습니다.",
        category: "HISTORY",
        difficulty: "NORMAL",
        gpReward: 20,
        orderIndex: 33,
    },
    {
        question: "2022 LoL 롤드컵(Worlds)에서 우승한 팀은?",
        optionA: "DRX",
        optionB: "T1",
        optionC: "Gen.G",
        optionD: "Damwon Gaming",
        answer: "A",
        explanation: "DRX는 2022년 롤드컵에서 예선을 거쳐 극적으로 우승하며 e스포츠 역사상 최고의 드라마 중 하나를 써냈습니다.",
        category: "HISTORY",
        difficulty: "NORMAL",
        gpReward: 20,
        orderIndex: 34,
    },
    {
        question: "2023 LoL 롤드컵(Worlds)에서 우승한 팀은?",
        optionA: "T1",
        optionB: "JDG Intelligence",
        optionC: "Gen.G",
        optionD: "NRG Esports",
        answer: "A",
        explanation: "T1은 2023년 롤드컵에서 Faker의 4번째 우승을 이끌며 결승에서 Weibo Gaming을 꺾었습니다.",
        category: "HISTORY",
        difficulty: "NORMAL",
        gpReward: 20,
        orderIndex: 35,
    },

    // ──────────────────────────────────────────────────────────────
    // DB 기반 — 2025~2026 시즌 결과 (NORMAL~HARD)
    // ──────────────────────────────────────────────────────────────
    {
        question: "2025 LCK Summer 결승전에서 우승한 팀은?",
        optionA: "Gen.G Esports",
        optionB: "Hanwha Life Esports",
        optionC: "T1",
        optionD: "KT Rolster",
        answer: "A",
        explanation: "2025 LCK Summer 결승에서 Gen.G가 Hanwha Life Esports를 3-1로 꺾고 우승했습니다.",
        category: "HISTORY",
        difficulty: "NORMAL",
        gpReward: 20,
        orderIndex: 36,
    },
    {
        question: "2025 LCK Summer 결승에서 Gen.G와 맞붙은 팀은?",
        optionA: "Hanwha Life Esports",
        optionB: "T1",
        optionC: "KT Rolster",
        optionD: "Dplus KIA",
        answer: "A",
        explanation: "2025 LCK Summer 결승은 Gen.G vs HLE(Hanwha Life Esports) 대전이었으며, Gen.G가 3-1로 우승했습니다.",
        category: "HISTORY",
        difficulty: "NORMAL",
        gpReward: 20,
        orderIndex: 37,
    },
    {
        question: "2025 LCK Summer 결승 스코어는? (Gen.G vs HLE)",
        optionA: "3-1 (Gen.G 우승)",
        optionB: "3-0 (Gen.G 우승)",
        optionC: "3-2 (Gen.G 우승)",
        optionD: "3-1 (HLE 우승)",
        answer: "A",
        explanation: "2025 LCK Summer 결승은 Gen.G가 Hanwha Life Esports를 3-1로 꺾고 우승한 경기입니다.",
        category: "HISTORY",
        difficulty: "HARD",
        gpReward: 25,
        orderIndex: 38,
    },
    {
        question: "2026 LCK Split 1 결승전에서 우승한 팀은?",
        optionA: "Gen.G Esports",
        optionB: "BNK FEARX",
        optionC: "T1",
        optionD: "Dplus KIA",
        answer: "A",
        explanation: "2026 LCK Split 1 결승에서 Gen.G가 BNK FEARX를 3-0으로 꺾고 우승했습니다.",
        category: "HISTORY",
        difficulty: "NORMAL",
        gpReward: 20,
        orderIndex: 39,
    },
    {
        question: "2026 LCK Split 1 결승에서 Gen.G와 맞붙은 팀은?",
        optionA: "BNK FEARX",
        optionB: "T1",
        optionC: "Hanwha Life Esports",
        optionD: "KT Rolster",
        answer: "A",
        explanation: "2026 LCK Split 1 결승은 Gen.G vs BNK FEARX(BFX) 대전이었으며, Gen.G가 3-0으로 우승했습니다.",
        category: "HISTORY",
        difficulty: "NORMAL",
        gpReward: 20,
        orderIndex: 40,
    },
    {
        question: "2026 LCK Split 1 결승 스코어는? (Gen.G vs BNK FEARX)",
        optionA: "3-0 (Gen.G 우승)",
        optionB: "3-1 (Gen.G 우승)",
        optionC: "3-2 (Gen.G 우승)",
        optionD: "3-0 (BNK FEARX 우승)",
        answer: "A",
        explanation: "2026 LCK Split 1 결승에서 Gen.G는 BNK FEARX를 3-0 완승으로 꺾고 우승했습니다.",
        category: "HISTORY",
        difficulty: "HARD",
        gpReward: 25,
        orderIndex: 41,
    },

    // ──────────────────────────────────────────────────────────────
    // 게임 지식 추가 (NORMAL~HARD)
    // ──────────────────────────────────────────────────────────────
    {
        question: "LoL에서 '억제기(Inhibitor)'를 파괴하면 어떤 효과가 발생하나요?",
        optionA: "해당 라인에 슈퍼 미니언이 스폰",
        optionB: "상대 넥서스 체력이 50% 감소",
        optionC: "모든 포탑이 일시 비활성화",
        optionD: "아군 미니언이 2배로 증가",
        answer: "A",
        explanation: "억제기를 파괴하면 해당 라인에 강력한 '슈퍼 미니언'이 스폰되어 라인 압박이 극대화됩니다.",
        category: "RULES",
        difficulty: "NORMAL",
        gpReward: 20,
        orderIndex: 42,
    },
    {
        question: "LoL에서 '판테온(Pantheon)의 W' 스킬처럼, LCK에서 '전방 강하'란?",
        optionA: "특정 지점에 착지해 광역 피해를 주는 궁극기 개념",
        optionB: "상대 팀 넥서스에 바로 이동하는 전략",
        optionC: "미니언 웨이브를 건너뛰는 전술",
        optionD: "서포터가 원딜 대신 딜을 넣는 전략",
        answer: "A",
        explanation: "LoL에서 전방 강하(Global Ult) 개념은 원하는 지점에 착지해 광역 피해를 주는 궁극기 스타일을 의미합니다.",
        category: "RULES",
        difficulty: "HARD",
        gpReward: 25,
        orderIndex: 43,
    },
    {
        question: "LCK 경기에서 '퍼스트 블러드(First Blood)'란?",
        optionA: "경기 중 첫 번째로 챔피언을 처치하는 것",
        optionB: "첫 번째 드래곤 처치",
        optionC: "첫 번째 바론 처치",
        optionD: "첫 번째 포탑 파괴",
        answer: "A",
        explanation: "퍼스트 블러드는 경기에서 첫 번째로 적 챔피언을 처치하는 것으로, 처치자에게 추가 골드가 지급됩니다.",
        category: "RULES",
        difficulty: "EASY",
        gpReward: 15,
        orderIndex: 44,
    },
    {
        question: "LCK 경기에서 '갱킹(Ganking)'의 의미는?",
        optionA: "정글러가 라인에 기습 개입하여 적을 처치하는 전술",
        optionB: "팀 전체가 한 라인에 집결하는 전략",
        optionC: "상대 정글 몬스터를 훔치는 행위",
        optionD: "아이템을 구매하기 위해 기지로 귀환하는 것",
        answer: "A",
        explanation: "갱킹은 정글러(또는 다른 라이너)가 라인에 몰래 접근하여 적을 기습 처치하는 핵심 전술입니다.",
        category: "RULES",
        difficulty: "EASY",
        gpReward: 15,
        orderIndex: 45,
    },
]
